services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    tty: true
    image: chatbot-sample
    container_name: chatbot-sample-container
    environment:
      TZ: 'Asia/Tokyo'
    network_mode: 'host'
